### ISSUE TITLE
Config.Item in Warehouse Lua

### ISSUE THREAD

**Issue by KikiLuvzU** [Virgildev/v-supplychain-restaurants#1]
Hello, we are absolutely in love with your script but I had a request/suggestion. The Warehouse config ask for Items "NAMES" which exposes your servers spawn names making it easier for hacks. The farming items allows for a "Label" instead. Could the config.items also be changed in that way? Thanks. 
Exp. My "bulk_fruit" or "chair_blue" is listed as such in the menu where everyone will choose which orders to fulfill. 
Thanks

**Comment by Virgildev** [comment]
This is fixed in the most recent release/push

**Comment by KikiLuvzU** [comment]
Thanks a ton!! I LOOOOVE this. Hope to see more immersive scripts from you. Good job

**Comment by KikiLuvzU** [comment]
Hi,I'm still having issues with this. Trying to join a discord or something. At this point I must be missing something. It works if I use your preconfigured but not if i added items.

**Comment by Virgildev** [comment]
Send me a DM on discord _Virgil7399_
